# Generated by Django 3.1.3 on 2020-11-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='Nothing', on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_item', models.CharField(default='no text', max_length=200)),
                ('schedule_time', models.TimeField()),
                ('person', models.ForeignKey(default='Nobody', on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
