# Generated by Django 3.1.3 on 2020-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(blank=True, verbose_name='previous time'),
        ),
    ]
