# Generated by Django 3.1.3 on 2020-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201121_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous time'),
        ),
    ]
